name: 'Template Repository Usage Action'
description: 'A GitHub action to automatically update a template repository README with a list of repos that used it in an organisation.'
author: 'Matthew Elphick'
inputs:
  token:
    required: true
    description: 'A personal access token that can access your organisation repos, see https://docs.github.com/en/github/authenticating-to-github/creating-a-personal-access-token for more.'
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  color: 'gray-dark'
  icon: 'git-branch'
