name: 'Find GitHub Template Repository Children'
description: 'A GitHub action for finding which repositories, under a single user/organization, are using a certain template.'
author: 'David Lorenzo'
inputs:
  token:
    required: true
    description: 'A personal access token that can access your organisation repos, see https://docs.github.com/en/github/authenticating-to-github/creating-a-personal-access-token for more.'
    default: ${{ github.token }}
  org:
    required: false
    description: 'A way to override the organisation the action is checking for usage of the template'
  repo:
    required: false
    description: 'A way to override the repo the action is checking for usage of in the given org'
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  color: 'gray-dark'
  icon: 'git-branch'
