name: "Build"
on:
  push:
    branches:
      - "**"
      - "!main"
    paths:
      - "src/**"
      - "package.json"
      - ".github/workflows/build.yaml"
  workflow_dispatch: {}

jobs:
  Build:
    name: "Build & Push"
    runs-on: "ubuntu-latest"
    steps:
      # Checkout
      - name: "Checkout"
        uses: "actions/checkout@v3"

      # Build
      - name: "npm install"
        run: "npm install"
      - name: "npm build"
        run: "npm run build"
      - name: "npm package"
        run: "npm run package"

      # Commit & Push
      - name: "List changes"
        run: "git status"
      - name: "Commit & Push changes"
        uses: "EndBug/add-and-commit@8b817249e9bc4aac26a3dbf27ab69f410c1baf19"
        with:
          add: "."
          push: "true"
          message: "Build"
